set(TARGET_FLAGS "-mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard")
set(LINKER_SCRIPT "${CMAKE_CURRENT_LIST_DIR}/stm32l4xx_flash.ld")

string(APPEND CMAKE_C_FLAGS " ${TARGET_FLAGS}")
string(APPEND CMAKE_ASM_FLAGS " ${TARGET_FLAGS}")
string(APPEND CMAKE_CXX_FLAGS " ${TARGET_FLAGS}")
string(APPEND CMAKE_EXE_LINKER_FLAGS " -T${LINKER_SCRIPT}")
