SUDO ?= sudo
STM32_FAMILY ?=

PROJECT_DIR := $(shell pwd)
MAIN_DIR := $(PROJECT_DIR)/main
BUILD_DIR := $(PROJECT_DIR)/build
SCRIPTS_DIR := $(PROJECT_DIR)/scripts
COMPONENTS_DIR := $(PROJECT_DIR)/components
SUBMODULES_DIR := $(PROJECT_DIR)/submodules
REQUIREMENTS_DIR := $(PROJECT_DIR)/requirements

CMAKE_FLAGS ?= -DSTM32_FAMILY=$(STM32_FAMILY)
