SUDO ?= sudo
PROJECT_NAME ?= project
BUILD_TYPE ?= Debug

PROJECT_DIR := $(shell pwd)
MAIN_DIR := $(PROJECT_DIR)/main
BUILD_DIR := $(PROJECT_DIR)/build
CUBEMX_DIR := $(PROJECT_DIR)/cubemx
SCRIPTS_DIR := $(PROJECT_DIR)/scripts
COMPONENTS_DIR := $(PROJECT_DIR)/components
SUBMODULES_DIR := $(PROJECT_DIR)/submodules
REQUIREMENTS_DIR := $(PROJECT_DIR)/requirements

PROJECT_BINARY := $(BUILD_DIR)/main/main.elf

CMAKE_FLAGS ?= 
CMAKE_FLAGS += -DCMAKE_PROJECT_NAME=$(PROJECT_NAME) -DCMAKE_BUILD_TYPE=$(BUILD_TYPE)
